language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  # express server on ci server listen on 3000
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  # nohup: if shell is closed, dont kill anything this command create
  # &: run command in a subshell in background
  - nohup npm run start &
  - sleep 3
  - npm run test
